# docker-compose.yml
version: '3'
services:
    node:
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USERNAME: postgres
            POSTGRES_DB: whatzpoppin
            POSTGRES_HOST: docker.for.mac.localhost
            POSTGRES_PORT: 5432
        volumes:
            - ../:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '9229:9229'
        command: ['yarn', 'run', 'docker-nodemon']